[project]
name = "zutun"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "humanize>=4.12.3",
    "pillow>=11.2.1",
    "sanic>=25.3.0",
]
